# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: postgres
  password: postgres

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: d5meludsrtee93
  pool: 5
  username: yxfxnqhkxatlyq
  password: 623d57c78a1b7e834140322a773219ee869e3d85ec6c9c83021f47a94b8fb97e

cucumber:
  <<: *TEST